dataset_url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(dataset_url, "Dataset.zip")
unzip("Dataset.zip")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
data$Time <- format(data$Time, format="%H:%M:%S")
data$Global_active_power <- as.numeric(data$Global_active_power)
data$Global_reactive_power <- as.numeric(data$Global_reactive_power)
data$Voltage <- as.numeric(data$Voltage)
data$Global_intensity <- as.numeric(data$Global_intensity)
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
data1 <- subset(data, (Date >= "2007-02-01") & (Date <= "2007-02-02"))
datetime <- paste(data1$Date, data1$Time)
data1$Datetime <- as.POSIXct(datetime)
png("plot2.png", width=480, height=480)
plot(x=data1$Datetime, y=data1$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()